[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3 --log-format defmt"

[env]
DEFMT_LOG="info"
ESP_RTOS_CONFIG_SW_TASK_OVERFLOW_DETECTION = "true"
ESP_RTOS_MAIN_STACK_SIZE = "32768"

[build]
rustflags = [
  # "-C", "link-arg=-nostartfiles",
  # "-C", "link-arg=-zstack-size=32768", 
  # "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]
